// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXEz-1LlSvjU2bODCYak15RAExQz__pi8',
    appId: '1:1069058058728:web:480bdee83cafc393e5dc5d',
    messagingSenderId: '1069058058728',
    projectId: 'cashbook-4b0ec',
    authDomain: 'cashbook-4b0ec.firebaseapp.com',
    storageBucket: 'cashbook-4b0ec.firebasestorage.app',
    measurementId: 'G-BV88P38HHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqAGcQQtFTspRiBSGEi510jEbdFZfAHcA',
    appId: '1:1069058058728:android:cc849f137bb8ab29e5dc5d',
    messagingSenderId: '1069058058728',
    projectId: 'cashbook-4b0ec',
    storageBucket: 'cashbook-4b0ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3GYLQAuoEHq1U4xH6ZussAtIWbhKHaSA',
    appId: '1:1069058058728:ios:95f734b9f5c85a7de5dc5d',
    messagingSenderId: '1069058058728',
    projectId: 'cashbook-4b0ec',
    storageBucket: 'cashbook-4b0ec.firebasestorage.app',
    iosBundleId: 'com.antigravity.cashbookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3GYLQAuoEHq1U4xH6ZussAtIWbhKHaSA',
    appId: '1:1069058058728:ios:95f734b9f5c85a7de5dc5d',
    messagingSenderId: '1069058058728',
    projectId: 'cashbook-4b0ec',
    storageBucket: 'cashbook-4b0ec.firebasestorage.app',
    iosBundleId: 'com.antigravity.cashbookApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXEz-1LlSvjU2bODCYak15RAExQz__pi8',
    appId: '1:1069058058728:web:2ec2645d61cdf9dee5dc5d',
    messagingSenderId: '1069058058728',
    projectId: 'cashbook-4b0ec',
    authDomain: 'cashbook-4b0ec.firebaseapp.com',
    storageBucket: 'cashbook-4b0ec.firebasestorage.app',
    measurementId: 'G-QQ526010RP',
  );
}
